# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spiceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtWidgets

from src.ui.widgets.FromFile_Window_design import FromFile_Window_design
# from FromFile_Window_ui import FromFile_Window_ui


class FromFile_Window(QtWidgets.QDialog, FromFile_Window_design):

    def __init__(self, *args, **kargs) -> None:
        super().__init__(*args, **kargs)
        self.setupUi(self)

        self.pathBtn.clicked.connect(self.selectFile)
        self.okBtn.clicked.connect(self.okBtnClick)

    def selectFile( self ):
        ''' Called when the user presses the Browse button
        '''
        self.fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
                        None,
                        "Select File",
                        "",
                        "Simulation Files (*.txt | *.csv);;Text File (*.txt);;CSV File (*.csv)",
                        )
        if self.fileName:
            self.pathT.setText(self.fileName)

    def okBtnClick(self):
        # Si los campos no estan vacios, se vuelve sin error
        if (self.nombreT.text() and self.pathT.text()):
            self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = FromFile_Window()
    ui.show()
    sys.exit(app.exec_())
