# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spiceWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtWidgets

from src.ui.widgets.FromFile_Window_design import FromFile_Window_design
# from FromFile_Window_design import FromFile_Window_design


class FromFile_Window(QtWidgets.QDialog, FromFile_Window_design):

    def __init__(self, ureg, *args, **kargs) -> None:
        super().__init__(*args, **kargs)
        self.setupUi(self)

        self.pathBtn.clicked.connect(self.selectFile)
        self.okBtn.clicked.connect(self.okBtnClick)

        # Valores de retorno
        self.name = ''              # Nombre de la curva
        self.path = ''              # Path del archivo
        self.type = self.comboBox.currentIndex()    # Opcion seleccionada (fercuencia o tiempo)
        self.freqUnits = ureg.rps

    def selectFile( self ):
        ''' Called when the user presses the Browse button
        '''
        self.fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
                        None,
                        "Select File",
                        "",
                        "Simulation Files (*.txt | *.csv);;Text File (*.txt);;CSV File (*.csv)",
                        )
        if self.fileName:
            self.pathT.setText(self.fileName)

    def okBtnClick(self):
        # Si los campos no estan vacios, se vuelve sin error
        self.name = self.nombreT.text()
        self.path = self.pathT.text()
        if (self.name and os.path.exists(self.path)):
            self.type = self.comboBox.currentIndex()
            self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = FromFile_Window()
    ui.show()
    sys.exit(app.exec_())
