# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PlotWidget import PlotWidget


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 279)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.numeradorL = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numeradorL.sizePolicy().hasHeightForWidth())
        self.numeradorL.setSizePolicy(sizePolicy)
        self.numeradorL.setObjectName("numeradorL")
        self.horizontalLayout_2.addWidget(self.numeradorL)
        self.numeradorT = QtWidgets.QLineEdit(Dialog)
        self.numeradorT.setInputMask("")
        self.numeradorT.setObjectName("numeradorT")
        self.horizontalLayout_2.addWidget(self.numeradorT)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.denominadorL = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.denominadorL.sizePolicy().hasHeightForWidth())
        self.denominadorL.setSizePolicy(sizePolicy)
        self.denominadorL.setObjectName("denominadorL")
        self.horizontalLayout.addWidget(self.denominadorL)
        self.denominadorT = QtWidgets.QLineEdit(Dialog)
        self.denominadorT.setInputMask("")
        self.denominadorT.setObjectName("denominadorT")
        self.horizontalLayout.addWidget(self.denominadorT)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.widgetTransferencia = PlotWidget(Dialog)
        self.widgetTransferencia.setObjectName("widgetTransferencia")
        self.verticalLayout_2.addWidget(self.widgetTransferencia)
        self.okBtn = QtWidgets.QPushButton(Dialog)
        self.okBtn.setStyleSheet("background-color: rgb(14, 51, 90);\n"
"color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:10px;\n"
"border-color:black;\n"
"")
        self.okBtn.setObjectName("okBtn")
        self.verticalLayout_2.addWidget(self.okBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.numeradorL.setText(_translate("Dialog", "Numerador:   "))
        self.numeradorT.setPlaceholderText(_translate("Dialog", "Ingrese los coeficientes separados por comas"))
        self.denominadorL.setText(_translate("Dialog", "Denominador:"))
        self.denominadorT.setPlaceholderText(_translate("Dialog", "Ingrese los coeficientes separados por comas"))
        self.okBtn.setText(_translate("Dialog", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
