# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'respuestaWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.ui.widgets.RespuestaWindow_design import Respuesta_Window_design
# from RespuestaWindow_design import Respuesta_Window_design

class Respuesta_Window(QtWidgets.QDialog, Respuesta_Window_design):

    def __init__(self, *args, **kargs):
        super().__init__(*args, **kargs)

        self.setupUi(self)

        self.amplitudT.setValidator(QtGui.QDoubleValidator())

        self.okBtn.clicked.connect(self.okBtnClick)

    def okBtnClick(self):
        self.accept()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ui = Respuesta_Window()
    ui.show()
    sys.exit(app.exec_())
